
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: friendship_app_development

test:
  <<: *default
  database: friendship_app_test

production:
  <<: *default
  database: friendship_app_production
  username: friendship_app
  password: <%= ENV['FRIENDSHIP_APP_DATABASE_PASSWORD'] %>
